name: lint

permissions: read-all

on:
  workflow_call:
    inputs:
      go:
        description: Go version
        default: 1.19
        required: false
        type: string

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ['1.19.x', '1.20.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # latest

      - name: Install Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # latest
        with:
          go-version: ${{ inputs.go }}
          check-latest: true

      - name: Lint
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # latest
        with:
          version: latest
          args: --timeout 5m
