name: test

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout with tags
        run: git fetch --prune --unshallow --tags

      - name: Create release
        run: |
          git log --format="%C(auto) %H %s" `git tag --sort=-committerdate | head -1`...HEAD > changelog.txt
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release create ${{ github.event.inputs.tag }} -t ${{ github.event.inputs.tag }} -F changelog.txt
